--[[
==============================================================================
Icons
==============================================================================

References:
  - https://www.nerdfonts.com/cheat-sheet
  - https://github.com/LunarVim/Launch.nvim/blob/master/lua/user/icons.lua
  - https://github.com/eyob721/papi721_nvim_config/blob/Lazyvim/lua/plugins/nvim-cmp.lua

--]]

return {
  kind_icons = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = "󰏿",
    Constructor = " ",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "󰇽",
    File = " ",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = " ",
    Keyword = "󰌋",
    Method = "m",
    Module = " ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = " ",
    Object = "󰠱",
    Operator = " ",
    Package = " ",
    Property = "󰜢",
    Reference = " ",
    Snippet = "",
    String = " ",
    Struct = " ",
    Text = "",
    TypeParameter = " ",
    Unit = "",
    Value = "󰎠",
    Variable = "󰂡",
  },
  git = {
    Branch = "",
    Diff = " ",
    FileDeleted = " ",
    FileIgnored = "◌",
    FileRenamed = " ",
    FileStaged = "S",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "U",
    LineAdded = " ",
    LineModified = " ",
    LineRemoved = " ",
    Octoface = " ",
    Repo = " ",
  },
  ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineLeft = "▎",
    BookMark = "",
    BoxChecked = "",
    Bug = " ",
    Calendar = "",
    Check = "",
    ChevronRight = "",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    ChevronShortUp = "",
    Circle = " ",
    Close = "󰅖",
    CloudDownload = " ",
    Code = "",
    Comment = "",
    Dashboard = "",
    DebugConsole = "",
    DividerLeft = "",
    DividerRight = "",
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    File = "",
    FileSymlink = "",
    Files = " ",
    FindFile = "󰈞",
    FindText = "󰊄",
    Fire = "",
    Folder = "󰉋 ",
    FolderOpen = " ",
    FolderSymlink = "",
    Forward = " ",
    Gear = " ",
    History = " ",
    Lightbulb = " ",
    LineLeft = "▏",
    LineMiddle = "│",
    List = " ",
    Lock = " ",
    NewFile = " ",
    Note = " ",
    Package = " ",
    Pencil = "󰏫 ",
    Plus = " ",
    Project = " ",
    Scopes = "",
    Search = " ",
    SignIn = " ",
    SignOut = " ",
    Stacks = "",
    Tab = "󰌒 ",
    Table = " ",
    Target = "󰀘 ",
    Telescope = " ",
    Text = " ",
    Tree = "",
    Triangle = "󰐊",
    TriangleShortArrowDown = "",
    TriangleShortArrowLeft = "",
    TriangleShortArrowRight = "",
    TriangleShortArrowUp = "",
    Watches = "󰂥",
  },
  diagnostics = {
    BoldError = "",
    BoldHint = "",
    BoldInformation = "",
    BoldQuestion = "",
    BoldWarning = "",
    Debug = "",
    Error = "",
    Hint = "󰌶",
    Information = "",
    Question = "",
    Trace = "✎",
    Warning = "",
  },
  misc = {
    CircuitBoard = "",
    Package = "",
    Robot = "󰚩 ",
    Smiley = "",
    Squirrel = "",
    Tag = "",
    Watch = "",
  },
}
